version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run test-ci
      - run: npx codecov
